repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        exclude: conda/meta.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: \.[j]sx?|\.css$  # *.js, *.jsx and css
        types: [file]
        exclude: docs/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        files: \.[j]sx?$  # *.js and *.jsx
        types: [file]
        exclude: docs/
        additional_dependencies:
        - 'eslint@8.15.0'
        - '@babel/core@^7.17.10'
        - '@babel/eslint-parser@^7.17.0'
        - '@babel/preset-react@^7.16.7'
        - 'eslint-config-airbnb@^18.1.0'
